import './globals.css'
import { Inter } from 'next/font/google';
import Document, { Html, Head, Main, NextScript } from "next/document";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Demo page',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        </body>
    </html>
  )
}
